### ISSUE TITLE
supersu folder x86_64 not found

### ISSUE THREAD

**Issue by kryokil** [m2sup3rn0va/RASEv1#2]
Hey buddy, finally got rooted api 28 (android 9) i had to however rename x86 folder to x86_64 inside supersu.zip in order to complete installation (this might be detected based on img you are rooting i think). Only posting this in case somebody else ran into same issue. Many thanks for all the hard work :)

**Comment by m2sup3rn0va** [comment]
Hey

Many thanks for this.
I only tested x86 version and yes, the script checks the config file to determine the arch of the Android installed.

I am updating the `supersu.zip` file just in case anyone falls into the same pit.

Thank you again.
